apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1
spec:
  selector:
    matchLabels:
      app: demo1
  template:
    metadata:
      labels:
        app: demo1
    spec:
      containers:
        - name: demo1
          image: oztinaz/demo1
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo1
spec:
  type: NodePort
  selector:
    app: demo1
  ports:
    - port: 8000
      targetPort: 8080
